### ISSUE TITLE
The 256, 192 and divide by 4

### ISSUE THREAD

**Issue by lamhoson** [kentaroy47/apple-lidar-stream#1]
Would you mind sharing with me the reason of divide by 4 and what is the meaning of 256, 192?

![image](https://user-images.githubusercontent.com/34258914/128827331-2d821f33-6b51-41ba-ba72-f7cd91de6277.png)

**Comment by kentaroy47** [comment]
256,192 comes from the lidar depth image resolution.
https://github.com/marek-simonik/record3d/issues/7

I cannot remember why I added the divide by four..(why you should always comment on your codes..)
Perhaps to match the actual intrinsic parameters instead of the given parameters from record3d.

**Comment by lamhoson** [comment]
Noted with many thanks.  If divide by 4 is a correction factor for your iPhone/iPad, would it same if i use iPhone12 Pro ?

**Comment by kentaroy47** [comment]
@lamhoson 
since it uses the same sensors, it should work with iPhone 12 as well. please try

**Comment by kentaroy47** [comment]
closing.

**Comment by saurabheights** [comment]
Color image is (960, 720, 3) 
Depth Imae is (256, 192) 

The resolution diffeerence is 960/256 = 3.75
Thus fx, fy, cx and cy needs to be scaled - https://stackoverflow.com/questions/74749690/how-will-the-camera-intrinsics-change-if-an-image-is-cropped-resized

Not sure why division is by 4 though. Maybe resolution between camera model is different between the one I had and one used by you.

@kentaroy47 @lamhoson
