### ISSUE TITLE
Can't install open3d

### ISSUE THREAD

**Issue by vittoema96** [kentaroy47/apple-lidar-stream#3]
I'm trying to install this project on an iPad-Pro.

I'm using Pyto to run python code

Whenever i try to install open3d it says:

`This package cannot be installed because it needs to be compiled, and iOS app cannot dynamically load external binaries`

What should i do?

**Comment by kentaroy47** [comment]
might be difficult to run open3d on iPad, use a PC

**Comment by vittoema96** [comment]
Oh ok, i thought this project was running Open3D on iPad, but it is actually just using the iPad as an input device for the PC, correct?

**Comment by kentaroy47** [comment]
> but it is actually just using the iPad as an input device for the PC,
Yes!
